require 'rake/clean'

SRCS = FileList["*.cpp"]
EXES = SRCS.ext("exe")
DSYM = SRCS.ext("exe.dSYM")

task :default => EXES

INCLUDE  = '-I/opt/local/include'
CXX      = 'g++'
#CXXFLAGS = "-O2 -Wall -lefence -ggdb #{INCLUDE}"
CXXFLAGS = "-Wall #{INCLUDE}"

LD_LIBRARY_PATH = '-L/opt/local/lib'
LIBS            = "-lboost_unit_test_framework-mt"
LDFLAGS         = "#{LD_LIBRARY_PATH} #{LIBS}"

rule '.exe' => '.cpp' do |t|
  sh "#{CXX} #{t.source} -o #{t.name} #{CXXFLAGS} #{LDFLAGS}"
end

CLEAN.include(EXES, DSYM, 'a.out')
