require 'rake/clean'

SRCS = FileList["*.cpp"]
EXES = SRCS.ext("exe")

task :default => EXES

CXX = 'g++'
CXXFLAGS = ''
LIBFLAGS = ''

rule '.exe' => '.cpp' do |t|
  sh "#{CXX} #{t.source} -o #{t.name} #{CXXFLAGS} #{LIBFLAGS}"
end

CLEAN.include(EXES)
CLEAN.include('a.out')
